services:
  ftp:
    image: delfer/alpine-ftp-server
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      - USERS=one|12345678|/home/in
      - ADDRESS=localhost
    restart: always