PUT http://localhost:9091/users/session_booking/2?isBooked=true&studentId=1
Content-Type: application/json
Autherization: eiwofijwoiej

PUT http://localhost:9091/users/session_booking/2?isBooked=true&studentId=2
Content-Type: application/json
Autherization: eiwofijwoiej
