# Create a Tutor
POST http://localhost:9091/users/tutors
Content-Type: application/json

{
    "tutorId": "TUT004",
    "firstName": "John",
    "lastName": "Doe",
    "email": "john.doe@example.com",
    "password" : "johnpass",
    "experienceYears": 5,
    "subjectsSubjectId" : "SUB005",
    "price" : 30

}

# Create a Student
POST http://localhost:9091/users/students
Content-Type: application/json

{
    "studentId": "STU005",
    "firstName": "Jane",
    "lastName": "Doe",
    "email": "jane.doe@example.com",
    "password" : "janepass"
}

# Create an Appointment
POST http://localhost:9091/users/sessions
Content-Type: application/json

{
    "sessionId": "SES004",
    "tutorTutorId": "TUT004",
    "studentStudentId": "STU005",
    "sessionTime": {
        "year": 2024,
        "month": 10,
        "day": 5,
        "hour": 14,
        "minute" : 00
    },
    "duration": 60,
    "status" : "SCHEDULED",
    "isBooked" : true
}

# Get Sessions for a Tutor
GET http://localhost:9091/users/tutor/TUT001/sessions?year=2024&month=10&day=5&hour=10

GET http://localhost:9091/users/students/STU005

PATCH http://localhost:9091/users/sessions/SES004
Content-Type: application/json

"CANCELLED"

PUT http://localhost:9091/users/sessions/SES002/reschedule
Content-Type: application/json

{
    "sessionTime": {
        "year": 2024,
        "month": 10,
        "day": 25,
        "hour": 18,
        "minute" : 00
    },
    "duration": 30
}
